// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    MqttConnectionParams: typeof import('./src/components/MqttConnectionParams.vue')['default']
    MqttMessages: typeof import('./src/components/MqttMessages.vue')['default']
    MqttSubscriptions: typeof import('./src/components/MqttSubscriptions.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VAlert: typeof import('vuetify/lib')['VAlert']
    VApp: typeof import('vuetify/lib')['VApp']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VCard: typeof import('vuetify/lib')['VCard']
    VList: typeof import('vuetify/lib')['VList']
    VListItem: typeof import('vuetify/lib')['VListItem']
    VSimpleTable: typeof import('vuetify/lib')['VSimpleTable']
    VTextarea: typeof import('vuetify/lib')['VTextarea']
    VTextField: typeof import('vuetify/lib')['VTextField']
  }
}
